app/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'app'

urlpatterns = [
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix
    path('', views.redirect_landing_page, name='redirect'),
    path('about/', TemplateView.as_view(template_name='app/about.html'), name='about'),

    # idea views
    path('idea/', views.IndexView.as_view(), name='index'),
    path('idea/<int:pk>/', views.IdeaDetail.as_view(), name='detail'),
    path('idea/add/', views.add_idea, name='add'),
    path('idea/<int:pk>/edit/', views.IdeaUpdate.as_view(), name='edit'),
    path('idea/<int:pk>/delete/', views.delete_idea, name='delete'),
    # note views
    path('idea/<int:pk_idea>/note/add/', views.add_note, name='add-note'),
    path('idea/<int:pk_idea>/note/<int:pk_note>', views.edit_note, name='edit-note'),
    path('idea/<int:pk_idea>/note/<int:pk_note>/delete/', views.delete_note, name='delete-note'),

    # tag views
    path('tag/', views.TagIndex.as_view(), name='tag-index'),
    path('tag/<int:pk>/', views.TagDetail.as_view(), name='tag-detail'),
    path('tag/add/', views.TagCreate.as_view(), name='tag-add'),
    path('tag/<int:pk>/edit/', views.TagUpdate.as_view(), name='tag-edit'),
    path('tag/<int:pk>/delete/', views.TagDelete.as_view(), name='tag-delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django import forms


class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, blank=True)
    color = models.CharField(max_length=7, default='#FF0000')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:tag-detail', kwargs={'pk': self.pk})


class Idea(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=5000, blank=True)
    creation_date = models.DateTimeField('date created', auto_now=True)
    update_date = models.DateTimeField('date updated', auto_now=True)
    # cascade: delete idea when owner is deleted
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    # access tags via <idea>.tags.all(); or vice versa: <tag>.idea_set.all()
    tags = models.ManyToManyField(Tag, blank=True)

    # image upload works, but uploaded images are not stored and served by heroku in production --> disabled for now
    # https://stackoverflow.com/a/41648399/2745116
    # https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
    # image = models.ImageField(upload_to='images', blank=True)
    # TODO: duration, milestones, notes

    @property
    def user_tags(self):
        """All tags that belong to the owner"""
        return Tag.objects.filter(owner=self.owner).order_by('name')

    def has_tag(self, tag):
        return Tag.objects.filter(id=tag.id, )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Absolute URL of an idea detail. Used for generic create/update views & model forms
        https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/#model-forms
        """
        return reverse('app:detail', kwargs={'pk': self.pk})


class Milestone(models.Model):
    name = models.CharField(max_length=200)
    # many-to-one: one idea may have many milestones but not vice versa
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000, blank=True)
    date = models.DateField('target date', blank=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField('when the milestone was completed', blank=True, null=True)

    def __str__(self):
        return self.name

    def complete(self):
        self.completed = True

    def uncomplete(self):
        self.completed = False


class Note(models.Model):
    """An arbitrary note belonging to an idea with a title and the note itself."""
    title = models.CharField(max_length=100)
    note = models.TextField(max_length=5000)
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

app/templates/app/about.html
{% extends 'app/base.html' %}

{% block content %}
<div style="text-align: center; margin-bottom: 2cm;">
    <i class="card-img-top fas fa-lightbulb fa-10x"></i>
    <h5>Ideally: Organize & Grow Your Ideas</h5>
</div>

{#    Features #}
<div class="card-group" style="text-align: center;">
    <div class="card">
        <i class="card-img-top fas fa-list fa-7x"></i>
        <div class="card-body">
            <p class="card-text">
               Keep track of your ideas and organize them with tags.
            </p>
        </div>
    </div>
    <div class="card">
    <i class="card-img-top fas fa-seedling fa-7x"></i>
        <div class="card-body">
            <p class="card-text">Grow your ideas over time by adding notes.</p>
        </div>
    </div>
    <div class="card">
        <i class="card-img-top fas fa-mobile-alt fa-7x"></i>
        <div class="card-body">
            <p class="card-text">Take Ideally with you and add ideas wherever you are with whatever device you want.</p>
        </div>
    </div>
    <div class="card">
        <i class="card-img-top fab fa-github fa-7x"></i>
        <div class="card-body">
            <p class="card-text">
                Free and <a href="https://github.com/stefanbschneider/ideally" target="_blank">open source</a>.
            </p>
        </div>
    </div>
</div>

    <div style="text-align: center; margin-top: 1cm;">
        <p>But: Ideally is still experimental and there is no warranty whatsoever!</p>
        <p>To get started, sign up or log in.</p>
        <a href="{% url 'django_registration_register' %}" class="btn btn-primary">Sign Up</a>
        <a href="{% url 'login' %}" class="btn btn-primary">Log In</a>
        <p>Public demo account: "demo"/"publicdemo". Any entered data is public!</p>
    </div>

{% endblock %}

app/templates/app/base.html
{% load static %}
{% load pwa %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!--    Bootstrap CSS: must come before any other CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
<!--jQuery: Must be in head before any scripts using jQuery (eg, color picker) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--    Bootstrap Colorpicker Plugin -->
    <link href="https://unpkg.com/bootstrap-colorpicker@3.2.0/dist/css/bootstrap-colorpicker.css" rel="stylesheet">

    {# Google Analytics #}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133644626-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-133644626-3');
    </script>

    {# favicon: requires "load static" at top; https://realfavicongenerator.net ; then modify how static files are loaded  #}
{#    now handled automatically by django-pwa #}
    {#    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">#}
{#    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">#}
{#    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">#}
{#    <link rel="manifest" href="{% static 'site.webmanifest' %}">#}
{#    <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#ffffff">#}
{#    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">#}
{#    <meta name="msapplication-TileColor" content="#ffffff">#}
{#    <meta name="msapplication-config" content="{% static 'browserconfig.xml' %}">#}
{#    <meta name="theme-color" content="#ffffff">#}

    {# cookie banner #}
    <link rel="stylesheet" type="text/css" href="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.css"/><script src="https://cdn.wpcc.io/lib/1.0.2/cookieconsent.min.js" defer></script><script>window.addEventListener("load", function(){window.wpcc.init({"border":"thin","corners":"small","colors":{"popup":{"background":"#f6f6f6","text":"#000000","border":"#555555"},"button":{"background":"#555555","text":"#ffffff"}},"position":"bottom","transparency":"10","content":{"href":"https://www.websitepolicies.com/policies/view/bu81NMv1"}})});</script>

    {# django-pwa #}
    {% progressive_web_app_meta %}

    <title>Ideally</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
<!--        Branding and title -->
        <a class="navbar-brand" href="{% url 'app:redirect' %}">
            <i class="fas fa-lightbulb"></i>
            Ideally
        </a>
<!--        Menu toggle button when collapsed -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
<!--        Menu -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:index' %}">Ideas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app:tag-index' %}">Tags</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">Logout ({{ user.get_username }})</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'django_registration_register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content container">
        {% block content %}
        {% endblock %}

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    </div>

    {% include "includes/footer.html" %}

<!--    Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<!-- Bootstrap color picker -->
    <script src="https://unpkg.com/bootstrap-colorpicker@3.2.0/dist/js/bootstrap-colorpicker.js"></script>
</body>
</html>

app/templates/app/idea_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>{{ idea.title }}</h1>
    <p class="small">
        Created on: {{ idea.creation_date }}
        <br>
        Updated on: {{ idea.update_date }}
    </p>

    <p>Tags:
        {% for tag in idea.tags.all %}
            <a href="{% url 'app:tag-detail' tag.id %}"><span class="badge badge-primary" style="background-color: {{ tag.color }}">{{ tag.name }}</span></a>
        {% endfor %}
    </p>

    {% if idea.description != "" %}
        <div class="card" style="margin-bottom: 10px;">
            <div class="card-header">Description</div>
            <div class="card-body">
                <div class="card-text">{{ idea.description }}</div>
            </div>
        </div>
    {% endif %}

{#    TODO: move into extra html file and include #}
    {% if idea.milestone_set.exists %}
    <div class="card">
        <div class="card-header">Milestones</div>
        <ul class="list-group list-group-flush">
            {% for milestone in idea.milestone_set.all %}
                <li class="list-group-item">
                    {{ milestone.name }}
                    {% if  milestone.description != "" %}
                    <br>
                    <div class="small">{{ milestone.description }}</div>
                    {% endif %}

{#                FIXME: buttons and actions for completing, editing, removing milestones #}
{#                    <div style="display: inline-block;">#}
{#                        {% if milestone.completed %}#}
{#                        <a href="{{ milestone.uncomplete }}" class="btn btn-primary" style="margin: 5px;"><i class="fas fa-check-circle"></i> Completed</a>#}
{#                            <button type="button" class="btn btn-success" onclick="{{ milestone.uncomplete }}">Completed</button>#}
{#                        {% else %}#}
{#                        <button type="button" class="btn btn-primary" onclick="{{ milestone.complete }}">Completeeee</button>#}
{#                        <a href="{{ milestone.complete }}" class="btn btn-success" style="margin: 5px;"><i class="far fa-check-circle"></i> Completed</a>#}
{#                        {% endif %}#}
{#                        <a href="" class="btn btn-secondary" style="margin: 5px;"><i class="fas fa-edit"></i> Edit</a>#}
{#                        <a href="" class="btn btn-danger" style="margin: 5px;"><i class="fas fa-trash"></i> Delete</a>#}
{#                    </div>#}

                </li>
{#                    TODO: display description and date if available; later: complete, remove #}
            {% endfor %}
        </ul>
    </div>
    {% endif %}

{#    {% if idea.image == "" %}#}
{#        <p>No image uploaded for this idea.</p>#}
{#    {% else %}#}
{#        <img src="{{ idea.image.url }}" alt="Uploaded image for idea with URL {{ idea.image.url }}">#}
{#    {% endif %}#}

{#    notes #}
    <div class="card-columns">
        {% for note in idea.note_set.all %}
            <div class="card">
                <div class="card-header">{{ note.title }}</div>
                <div class="card-body">
                    <div class="card-text">{{ note.note }}</div>
                    <a href="{% url 'app:edit-note' idea.pk note.pk %}" class="btn btn-light" style="margin-top: 5px;"><i class="fas fa-edit"></i> Edit Note</a>
                    <button type="button" class="btn btn-light" data-toggle="modal" data-target="#deleteNoteModal"><i class="fas fa-trash"></i> Delete Note</button>
                </div>
            </div>

            {% url 'app:delete-note' idea.pk note.pk as delete_note_url %}
            {% include 'includes/confirm_delete_modal.html' with modal_id="deleteNoteModal" item_title=note.title delete_url=delete_note_url %}
        {% endfor %}
    </div>


    <a class="btn btn-primary" href="{% url 'app:add-note' idea.id %}"><i class="far fa-sticky-note"></i> Add Note</a>
    <a class="btn btn-secondary" href="{% url 'app:edit' idea.id %}"><i class="fas fa-edit"></i> Edit Idea</a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteIdeaModal"><i class="fas fa-trash"></i> Delete Idea</button>
    {% url 'app:delete' idea.pk as delete_idea_url %}
    {% include 'includes/confirm_delete_modal.html' with modal_id="deleteIdeaModal" item_title=idea.title delete_url=delete_idea_url %}
{% endblock %}

app/templates/app/idea_form.html
{% extends 'app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

app/templates/app/idea_index.html
{% extends 'app/base.html' %}

{% block content %}
    {% if idea_list %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Tags</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for idea in idea_list %}
            <tr>
                <td>
                    <a href="{% url 'app:detail' idea.id %}">{{ idea.title }}</a>
                    <br>
                    <div class="small">{{ idea.description }}</div>
                </td>
                <td>
                    {% for tag in idea.tags.all %}
                        <a href="{% url 'app:tag-detail' tag.id %}"><span class="badge badge-primary" style="background-color: {{ tag.color }}">{{ tag.name }}</span></a>
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'app:detail' idea.id %}" style="margin: 5px;" data-toggle="tooltip" data-placement="top" title="Detail">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a href="{% url 'app:edit' idea.id %}" style="margin: 5px;" data-toggle="tooltip" data-placement="top" title="Edit">
                        <i class="fas fa-edit"></i>
                    </a>

                    <dev data-toggle="tooltip" data-placement="top" title="Delete">
                        <a href="" style="margin: 5px;" data-toggle="modal" data-target="#{{ idea.title }}"><i class="fas fa-trash"></i></a>
                        {% url 'app:delete' idea.pk as delete_idea_url %}
                        {% include 'includes/confirm_delete_modal.html' with modal_id=idea.title item_title=idea.title delete_url=delete_idea_url %}
                    </dev>

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <p>No ideas added yet.</p>
    {% endif %}


<!--    add new button -->
    <a href="{% url 'app:add' %}" style="position: fixed; bottom: 1em; right: 1em;" data-toggle="tooltip" data-placement="top" title="Add new idea">
        <i class="fas fa-plus-circle fa-3x"></i>
    </a>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

{% endblock %}

app/templates/app/tag_delete.html
{% extends 'app/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete tag "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

app/templates/app/tag_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>{{ tag.name }}</h1>
    <p><span class="badge badge-primary" style="background-color: {{ tag.color }}">{{ tag.name }}</span></p>
    <p>Description: {{ tag.description }}</p>
    <p>Ideas with this tag:
        <ul>
            {% for idea in tag.idea_set.all %}
                <li><a href="{% url 'app:detail' idea.id %}">{{ idea.title }}</a></li>
            {% endfor %}
        </ul>
    </p>

<!--    <div class="demo">-->
<!--      <h1>Bootstrap Colorpicker Demo (with Bootstrap)</h1>-->
<!--      <input id="demo-input" type="text" value="rgb(255, 128, 0)" />-->
<!--    </div>-->

    <a class="btn btn-secondary" href="{% url 'app:tag-edit' tag.id %}">Edit <i class="fas fa-edit"></i></a>
    <a class="btn btn-danger" href="{% url 'app:tag-delete' tag.id %}">Delete <i class="fas fa-trash"></i></a>

    <script>
    $(function () {
      // Basic instantiation:
      $('#demo-input').colorpicker();

      // Example using an event, to change the color of the #demo div background:
      $('#demo-input').on('colorpickerChange', function(event) {
        $('#demo').css('background-color', event.color.toString());
      });
    });
  </script>
{% endblock %}

app/templates/app/tag_form.html
{% extends 'app/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
{#        {{ form.as_p }}#}

        <div class="form-group">
            {{ form.name.label_tag }}
            <input class="form-control" type="text" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" value="{{ form.name.value }}">
            {#    {% if form.help_text %}#}
            {#    <small class="form-text text-muted">{{ form.help_text }}</small>#}
            {#    {% endif %}#}
            {{ form.name.errors }}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            <input class="form-control" type="text" id="{{ form.description.id_for_label }}" name="{{ form.description.name }}" value="{{ form.description.value }}">
            {{ form.description.errors }}
        </div>
        <div class="form-group">
            {{ form.color.label_tag }}
            <input class="form-control" type="color" id="{{ form.color.id_for_label }}" name="{{ form.color.name }}" value="{{ form.color.value }}">
            {{ form.color.errors }}
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

app/templates/app/tag_index.html
{% extends 'app/base.html' %}

{% block content %}
    {% if tag_list %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Tag</th>
                <th scope="col">#Ideas</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for tag in tag_list %}
            <tr>
                <td>
                    <a href="{% url 'app:tag-detail' tag.id %}">{{ tag.name }}</a>
                    <br>
                    <div class="small">{{ tag.description }}</div>
                </td>
                <td><a href="{% url 'app:tag-detail' tag.id %}"><span class="badge badge-primary" style="background-color: {{ tag.color }}">{{ tag.name }}</span></a></td>
                <td>{{ tag.idea_set.count }}</td>
                <td>
                    <a href="{% url 'app:tag-detail' tag.id %}" style="margin: 5px;" data-toggle="tooltip" data-placement="top" title="Detail">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a href="{% url 'app:tag-edit' tag.id %}" style="margin: 5px;" data-toggle="tooltip" data-placement="top" title="Edit">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{% url 'app:tag-delete' tag.id %}" style="margin: 5px;" data-toggle="tooltip" data-placement="top" title="Delete">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <p>No tags added yet.</p>
    {% endif %}


<!--    add new button -->
    <a href="{% url 'app:tag-add' %}" style="position: fixed; bottom: 1em; right: 1em;" data-toggle="tooltip" data-placement="top" title="Add new tag">
        <i class="fas fa-plus-circle fa-3x"></i>
    </a>
    <script>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}